### ISSUE TITLE
TaurusGUI demo

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#10]
- [x] Copy TaurusGUI configuration from old tango-box to the new VM
- [x] Setup desktop link to start TaurusGUI with copied configuration
- [x] Make missing related device (servers) from tango-box run on demo-container

**Comment by cpt-majkel** [comment]
![error](https://user-images.githubusercontent.com/24622343/30638546-0eb68f82-9dfc-11e7-8299-19aa0b43d7a3.PNG)

I am encountering error as can be seen above. All labels on buttons ale visible only for 3-5s after startup and then they disappear. Situation with "label" is a bit different because it is fixed from the beginning (although declared label is different). To make it worse all labels in top right corner are correct :D
@sergirubio @andygotz  @Ingvord could you please help me?

**Comment by piogor** [comment]
Related issue is created in the tango-controls repo. So, this is going to be closed.
