### ISSUE TITLE
Compile QTango on the VM

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#11]
- [x] QTango compiled and installe in /usr/local
- [x] Check if any demo is available, see contacts below

For qtango support you can contact Giacomo Strangolino (giacomo.strangolino@elettra.eu), for e-giga you can contact Lucio Zambon (lucio.zambon@elettra.eu)

**Comment by stanislaw47** [comment]
I've problem while installing QTango. Firstly, I install 
```
sudo apt-get install -y qt4-default qt4-qmake qt4-default libqwt-dev libxmu-dev
```
Next, I get QTango sources from [here](http://www.tango-controls.org/media/filer_public/49/4a/494ac339-bb4d-437b-99fd-86a781c125ac)

Then I open `qtango.pri` and delete 
```
-lCOSNotify4 \
-lAttNotification4
```
because it was said [here](http://www.tango-controls.org/community/forum/c/general/installation/qtango-installation-error/?page=1#post-194) that these are required by older version of Tango and cause installation problems with `9.x.x`

After some experimentation I realised that QTango is meant to be installed where the sources are, because compiling it in custom `build` catalog led to errors.

So I just type `qmake` and `make` inside QTango catalog.
And the error is:
```
cd qtcontrols/ && make -f Makefile 
make[1]: Entering directory '/home/tango-cs/src/qtango-5.3.9/qtcontrols'
g++ -c -m64 -pipe -std=gnu++98 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DQTANGO_PRINTINFO -DQTANGO_VERSION_STR="\"5.3.9\"" -DQTANGO_VERSION=0x050309 -DVER_MAJ=5 -DVER_MIN=3 -DVER_FIX=9 -DSHAREDIR="\"/runtime/share\"" -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -I/usr/include\qwt -I/usr/local/include -I/usr/local/include/tango -I/usr/local/include -I/usr/local/include -I/usr/include/X11 -I../common -I.. -I../dbus -Imoc -Isrc -o obj/scrollzoomer.o src/scrollzoomer.cpp
src/scrollzoomer.cpp:2:29: fatal error: qwt_plot_canvas.h: No such file or directory
compilation terminated.
Makefile:620: recipe for target 'obj/scrollzoomer.o' failed
make[1]: *** [obj/scrollzoomer.o] Error 1
make[1]: Leaving directory '/home/tango-cs/src/qtango-5.3.9/qtcontrols'
Makefile:80: recipe for target 'sub-qtcontrols-make_default-ordered' failed
make: *** [sub-qtcontrols-make_default-ordered] Error 2
```

I've tried some magic tricks with `XXX_HOME` envs but the  outcome is still the same.

**Comment by stanislaw47** [comment]
Ok, I figured out that I need `qwt` version 5, which is, in theory, available on Ubuntu as `libqwt5-qt4`
The problem is, when I install it, QTango does not see it. I tried `locate` and I get only two, Python-related dirs, opposed to version 6 where I got whole wall of them.

**Comment by andygotz** [comment]
Maybe you need `libqwt5-qt4-dev` ?

**Comment by stanislaw47** [comment]
Thanks @andygotz, I'll try that

**Comment by stanislaw47** [comment]
Well, that doesn't make any difference. I'll try installing it from sources.

**Comment by stanislaw47** [comment]
Ok, it works now. QTango just needed Qwt installed from sources, somehow.

**Comment by stanislaw47** [comment]
I just find out that there is version 6.3.0 somewhere on Github. I've been installing version 5.3.9 from official Tango Website. IMO there should be at least an information that there is such [repo](https://github.com/ELETTRA-SincrotroneTrieste/cppqtclients/tree/master/qtango) with newer QTango. 
However, since this took me a while, I write it here down in case of need:

How to install QTango 5.3.9
==================

Dependencies:
---------------
Qt4
`sudo apt-get install -y qt4-default qt4-dev-tools`
XMU
`sudo apt-get inntall -y libxmu-dev`
Qwt:
There is package but you **MUST** build from sources. There is how:
```
wget https://sourceforge.net/projects/qwt/files/qwt/5.2.3/qwt-5.2.3.tar.bz2 -P /home/tango-cs/src
tar xvjf qwt-5.2.3.tar.bz2
cd qwt-5.2.3
qmake
make 
sudo make install
```
By default `Qwt` installs in `/usr/local/qwt-5.2.3`, but it can be changed in `qwtconfig.pri`

Now, let's install QTango:

```
wget http://www.tango-controls.org/media/filer_public/49/4a/494ac339-bb4d-437b-99fd-86a781c125ac/qtango-539tar.gz -P /home/tango-cs/src
cd /home/tango-cs/src
tar xvzf qtango-539tar.gz
```
Open qtango.pri make following changes:

- change qwt root (in this case, from `/usr/local/5.2.1` to just `/usr/local`)
`QWT_HOME = /usr/local/qwt-5.2.3`

- change Tango and OmniORb roots (in this case, just let it be both `/usr/local`)

- delete lines:
```
-lCOSNotify4 \
-lAttNotification4 \
```

- change `QMAKE_CXXFLAGS` from `-std=gnu++98` to `-std=c++0x` (just comment and uncomment proper lines)
- change `INSTALL_DIR` to `/usr/local`

Now, when everything is prepared, you can:
```
qmake
make 
sudo ./install
```

**WARNING** Compilation may last *very* long

Remember, do NOT create new catalog, i. e. build, to compile. This causes plenty of problems to solve.
Also, do NOT use `make install` because behaviour is unspecified.
If you want to have a clean source code, I recommend just delete whole qTango catalog and upack it again. 
If during Qtngo `make` you receive an erro saying `isnan was not declared in this scope` just change `isnan` to `std::isnan` in specified file

**Comment by stanislaw47** [comment]
How to install QTango 6.4.2 on TangoBox_RC_5
============================================

TangoBox already includes Tango, omniORB, zmq, and Qt stuff, for whole specification click [here](https://github.com/ELETTRA-SincrotroneTrieste/cppqtclients/blob/master/qtango/installation-ubuntu-16.04.txt)

Dependencies:
-------------

XMU and QtDesigner:
`sudo apt-get isntall -y libxmu-dev qt4-designer`


QTango:
-------

`git clone https://github.com/ELETTRA-SincrotroneTrieste/cppqtclients.git /home/tango-cs/src/qtango`

`cd /home/tango-cs/src/qtango/qtango`

Inside just edit `qtango.pri`:
```
QWT_HOME = /usr
QWT_INCLUDE=$${QWT_HOME}/include/qwt
INSTALL_ROOT=/usr/local
```

And that's it, you can just:
```
qmake
make
sudo make install
```
