### ISSUE TITLE
Install PyAlarm device servers

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#19]
PyAlarm shell be installed on a base docker image as well as on the VM
- [x] PyAlarm installed on VM
- [x] PyAlarm added to docker base image

**PyAlarm instances running on each container and on VM**
- [x] VM
- [x] base
- [x] archiving
- [x] web
- [x] sardana
- [x] sim

**Comment by sergirubio** [comment]
Hi, be sure to update to the latest fandango and panic releases (13.2/6.3 on github/pypi).

**Comment by cpt-majkel** [comment]
Hi, 
I've already updated fandango and it works fine. However, there is a problem with the latest panic release (6.3) . Previous version works well (alarm handling, gui) but 6.3 one doesn't. It shows that alarms are in "norm" state while DS are not working. In addition, gui also has some bugs (i.e "new" button has no effect). 
Here is the comparison of both versions (*ExampleAlarmBase* should not work because DS is not started):

![1](https://user-images.githubusercontent.com/24622343/30795445-dfb6a9bc-a1cd-11e7-8082-366ee0d1a31d.PNG)

I am not sure if this is only my case or this is some kind of a bug @sergirubio ?

**Comment by sergirubio** [comment]
... it's strange, did you restarted all devices after update? ... I'm going to try to reproduce the error and commit a patch.

**Comment by sergirubio** [comment]
Could you print out the result or exception of calling this:
panic.api()['Example_Alarm_Base'].get_ds().get_version()

In my current version all stop devices appear in OOSRV or ERROR state, could you get latests sources from develop and try again?


![image](https://user-images.githubusercontent.com/18418345/30802287-40c61bd0-a1e6-11e7-9c05-e42b87d93550.png)

**Comment by cpt-majkel** [comment]
Ok, i installed version 6.3.3 from delevop but the problem is still the same. Here is result of command 
(if i did it correctly :) )

![6 3 3](https://user-images.githubusercontent.com/24622343/30805490-f05f2b30-a1f1-11e7-95a0-6585d4addd9e.PNG)

After a while after stopping DS i got this: 

![picture](https://user-images.githubusercontent.com/24622343/30805516-07021618-a1f2-11e7-8403-b44f41a29c2e.PNG)

Here version 6.3.3 with DS down:

![6 3 3gui](https://user-images.githubusercontent.com/24622343/30805736-08c89318-a1f3-11e7-8380-5b6e1bd772c4.PNG)

The same with 6.3.2 one (from PyPi): 

![6 3 2](https://user-images.githubusercontent.com/24622343/30805548-256c1518-a1f2-11e7-9330-e8a754b14b5d.PNG)

**Comment by sergirubio** [comment]
... this is very strange and I cannot reproduce it. It is the VM ready somehow so I can give it a try directly there?

I also tried with fandango/panic installed from pip on a fresh docker ... cannot reproduce. I would need access to the VM to have a hint of what's going on.

**Comment by sergirubio** [comment]
I just did a patch to panic.AlarmAPI.load() method that may have some relationship with this

Please, try again using the latest sources from develop

**Comment by cpt-majkel** [comment]
I compared terminal traces of three versions of PANIC. First one is 6.0.6 which works fine - only calls are those about dead DS - it is correct. Below are two others (both have the same issue):

1.  Latest PyPi version

![error_634](https://user-images.githubusercontent.com/24622343/30850449-de1b3626-a2a5-11e7-943d-d0281749d72b.PNG)

2. Latest from develop

![error_633](https://user-images.githubusercontent.com/24622343/30850429-cf50eda2-a2a5-11e7-937c-51d8ef30041c.PNG)

**Comment by sergirubio** [comment]
WOW!, this is the first case of caseless dependent networking issues, sorry.
I just pushed a bug fix, try again from develop

**Comment by cpt-majkel** [comment]
Now everything works fine. Thanks for help! :)
